### ISSUE TITLE
octodns.provider.SupportsException: dnsmadeeasy: multi-value PTR records not supported for 4.3.2.1.in-addr.arpa. when using an alias

### ISSUE THREAD

**Issue by trustedip** [octodns/octodns-dnsmadeeasy#28]
This is what I have in my config:

```
  3.2.1.in-addr.arpa.:
    sources:
      - auto-arpa
    targets:
      - dnsmadeeasy

  port53.nl.:
    sources:
      - yaml
    targets:
      - dnsmadeeasy

  port53.net.:
    alias: port53.nl.
```

I enabled:  `auto_arpa: true`

running a octodns-sync with DNSME as the provider results in:octodns.provider.SupportsException: dnsmadeeasy: multi-value PTR records not supported for 4.3.2.1.in-addr.arpa. which seems to be intended.

The zone port53.nl contains an A record to 1.2.3.4 and because port53.net is an alias, it also has that A record.

Changing the provider and adding `strict_supports=False` stops it from throwing the error, but only the last PTR entry is retained, i.e. 4.3.2.1. mapping to ptrtest.port53.net.

in debug logs, I find: _multi-value PTR records not supported for 4.3.2.1.in-addr.arpa.; falling back to single value, ptrtest.port53.net._

In the DNSME UI and API I can add multiple PTR records for 4 in 3.2.1.in-addr.arpa.

It isn't clear to me if this is an issue with the provider or octodns base.py, which has:

```
                record._type == 'PTR'
                and len(record.values) > 1
                and not self.SUPPORTS_MULTIVALUE_PTR
            ):
                # replace with a single-value copy
                msg = f'multi-value PTR records not supported for {record.fqdn}'
                fallback = f'falling back to single value, {record.value}'
                self.supports_warn_or_except(msg, fallback)
                record = record.copy()
                record.values = [record.value]
                desired.add_record(record, replace=True)
```

which is only retaining the first value (I think).

Known limitation?
